# Configuration for the roar CLI
# https://github.com/JanMalch/roar

branch = "main"

[[update]]
file = "cmd/root.go"
find = "const VERSION = "
replace = "const VERSION = \"{{version}}\""

[changelog]
include = ["feat", "fix", "refactor"]
url_commit = "https://github.com/JanMalch/snips/commit/{{hash}}"
url_browse_at_tag = "https://github.com/JanMalch/snips/tree/v{{version}}"
url_compare_tags = "https://github.com/JanMalch/snips/compare/v{{previous}}...v{{version}}"
url_commits_for_tag = "https://github.com/JanMalch/snips/commits/v{{version}}"
